#! /bin/sh

# Mount Filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs devtmpfs /dev
mount -t tmpfs tmpfs /media

# /dev Basic Entries
mknod -m 600 /dev/console c 5 1
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/ptmx c 5 2
mknod -m 666 /dev/tty c 5 0
mknod -m 444 /dev/random c 1 8
mknod -m 444 /dev/urandom c 1 9

# /dev PTS Entries
mkdir /dev/pts
mount -t devpts devpts /dev/pts

# Setup Mdev
mdev -s
echo /sbin/mdev > /proc/sys/kernel/hotplug

# Mount boot partition
mount -t vfat /dev/mmcblk0p2 /boot

# Remount / as Read/Write (TMP)
mount -oremount,rw /
mkdir /mnt

# Load Kernel Modules
modprobe snd_bcm2835
modprobe hid_sony
modprobe evdev
modprobe joydev
#modprobe vc4

# Setup network (TODO: use a service to control the network instead of static infos)
#udhcpc eth0
ifconfig eth0 up
ifconfig eth0 10.0.0.20

# Adjust resolution
vcgencmd get_config sdtv_aspect set 1
/usr/sbin/fbset snes9x
